# Generated by Django 3.2.6 on 2022-03-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tfo', models.CharField(max_length=20)),
                ('universidad', models.CharField(max_length=30)),
            ],
        ),
    ]
