# Generated by Django 3.2.6 on 2022-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorEstrella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrella',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='direccion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='tfo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='universidad',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
