# Generated by Django 3.2.6 on 2022-03-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorEstrella', '0002_auto_20220327_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrella',
            name='link',
            field=models.URLField(null=True, verbose_name='http://dev.virtualearth.net/REST/v1/Routes/Driving?wp.1=<django.db.models.fields.CharField>&wp.2=<django.db.models.fields.CharField>,&key=Am3rc5_fSLkVOUrt2RNLAWIqdNgx3j2kxwyK-5mUd5gf5g59XJ8MMXUhJbcSZZvZ'),
        ),
    ]
