# Generated by Django 3.2.6 on 2022-03-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorEstrella', '0003_alter_estrella_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrella',
            name='link',
        ),
    ]
