# Generated by Django 3.2.6 on 2022-05-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracionPerdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('dinero', models.IntegerField()),
                ('perdida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracionGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('dinero', models.IntegerField()),
                ('ganancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.estudiante')),
            ],
        ),
    ]
